version: "3"

services:
  db:
    container_name: test-matomo-db
    image: mariadb
    command: --max-allowed-packet=64MB
    restart: always
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=
    env_file:
      - ./db.env

  app:
    container_name: test-matomo-app
    image:
      # Select your Matomo container from:
      # https://hub.docker.com/_/matomo
      matomo:4.13.0-fpm-alpine
    restart: always
    links:
      - db
    volumes:
      - ./config.ini.php:/var/www/html/config/config.ini.php
      #- ./logs:/var/www/html/logs
      - matomo:/var/www/html
    environment:
      - MATOMO_DATABASE_HOST=db
      - PHP_MEMORY_LIMIT=2048M
    env_file:
      - ./db.env

  web:
    container_name: test-matomo-web
    image: nginx:alpine
    restart: always
    volumes:
      - matomo:/var/www/html:ro
      # see https://github.com/matomo-org/matomo-nginx
      - ./matomo.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "8111:80"

volumes:
  db:
  matomo:
